apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  namespace: webapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp
        image: aungkyaws/python-webapp:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: userdb
